services:
  analytics-service:
    build: .
    container_name: analytics-service
    restart: unless-stopped
    ports:
      - "8091:8091"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@analytics-db:5432/${POSTGRES_DB}
      ORDER_SERVICE_URL: http://order-service:8082
      FRANCHISE_SERVICE_URL: http://franchise-service:8089
    depends_on:
      analytics-db:
        condition: service_healthy
    networks:
      - microservices-net

  analytics-db:
    image: postgres:17-alpine
    container_name: analytics-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - analytics_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  microservices-net:
    external: true
volumes:
  analytics_data:
